#include "gpios.h"

void configureGPIOs() {
    pinMode(PRESSURE_TRANSMITTER_PIN, INPUT);
    pinMode(PULSE_COUNTER_PIN, INPUT_PULLDOWN);
    pinMode(START_PUMP_BUTTON, INPUT_PULLDOWN);
    pinMode(VALVE_CONTROL_PIN, OUTPUT);

    pinMode(PUMP_ON_LIGHT_PIN, OUTPUT);
    pinMode(PUMP_OFF_LIGHT_PIN, OUTPUT);
    pinMode(ONBOARD_LED_PIN, OUTPUT); 
    pinMode(CIRCUIT_READINESS_LED, OUTPUT);
}
